version: '3'

services:
  node:
    image: "node:13"
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
    working_dir: /app
    command: npm run test
    
volumes:
  node_modules:
