type: object
definitions:
  location:
    type: array
    minItems: 2
    maxItems: 2
    items:
      - type: number
        description: Latitude
        minimum: -90
        maximum: 90
      - type: number
        description: Longitude
        minimum: -180
        maximum: 180
  osm:
    type: object
    minProperties: 1
    additionalProperties: false
    properties:
      relation:
        type: number
      way:
        type: number
  photo:
    type: object
    required:
      - src
      - license
      - attr
    additionalProperties: false
    properties:
      src:
        type: string
        format: uri
      href:
        type: string
        format: uri
      license:
        type: string
      attr:
        type: string
      year:
        type: number
  office:
    type: array
    minItems: 1
    items:
      type: object
      additionalProperties: false
      properties:
        location:
          $ref: '#/definitions/location'
        osm:
          $ref: '#/definitions/osm'
required:
  - name
  - location
  - copyright
  - license
additionalProperties: false
properties:
  name:
    type: string
    minLength: 1
  park:
    type: string
    minLength: 1
  region:
    type: string
    minLength: 1
  country:
    type: string
    minLength: 1
  location:
    $ref: '#/definitions/location'
  osm:
    $ref: '#/definitions/osm'
  iucn:
    type: string
    description: https://www.iucn.org/theme/protected-areas/about/protected-area-categories
    pattern: ^(Ia|Ib|II|III|IV|V|VI)$
  nearest_town:
    type: object
    required:
      - name
      - location
    additionalProperties: false
    properties:
      name:
        type: string
      location:
        $ref: '#/definitions/location'
  photos:
    type: array
    minItems: 1
    items:
      $ref: '#/definitions/photo'
  features:
    type: object
    minProperties: 1
    additionalProperties: false
    properties:
      rainforest:
        type: boolean
      canyon:
        type: boolean
      cliff_edges:
        type: boolean
      stairs:
        type: boolean
      stroller:
        type: boolean
      walk:
        type: boolean
      accessible:
        type: boolean
      mountain_bike:
        type: boolean
      slippery:
        type: boolean
      flood_risk:
        type: boolean
      stepping_stones_water_crossing:
        type: boolean
      loop:
        type: boolean
      lookout:
        type: boolean
      hikers_only:
        type: boolean
      dogs:
        type: boolean
      water:
        type: boolean
      toilet:
        type: boolean
      tree_fall_risk:
        type: boolean
      allocated_sites:
        type: boolean
      showers:
        type: boolean
      tables:
        type: boolean
      campfires:
        type: boolean
      gathering_firewood:
        type: boolean
      generators:
        type: boolean
      pets:
        type: boolean
      smoking:
        type: boolean
      amplified_music:
        type: boolean
      rubbish_bins:
        type: boolean
      drive_in:
        type: boolean
      horses:
        type: boolean
      bicycles:
        type: boolean
      firearms:
        type: boolean
      booking_required:
        type: boolean
      beach:
        type: boolean
      unesco_world_heritage:
        type: boolean
  access:
    type: object
    minProperties: 1
    additionalProperties: false
    properties:
      car:
        type: boolean
      sealed_road:
        type: boolean
      causeway:
        type: boolean
      hike_in:
        type: boolean
      motorcycle:
        type: boolean
      mountain_bike:
        type: boolean
      road_bicycle:
        type: boolean
      wheelchair:
        type: boolean
      boat:
        type: boolean
      kayak:
        type: boolean
  toilets:
    type: array
    minItems: 1
    items:
      type: object
  water:
    type: array
    minItems: 1
    items:
      type: object
  parking:
    type: array
    minItems: 1
    items:
      type: object
  fees:
    type: array
    minItems: 1
  park_office:
    $ref: '#/definitions/office'
  visitor_centre:
    $ref: '#/definitions/office'
  links:
    type: object
    minProperties: 1
    additionalProperties: false
    properties:
      official_website:
        type: string
        format: uri
      wikipedia:
        type: string
        format: uri
      wikivoyage:
        type: string
        format: uri
  copyright:
    type: string
    minLength: 1
  license:
    type: string
    minLength: 1
    pattern: ^CC BY\-NC\-SA 4\.0$
